name: 02 - Workflow Events
on: 
  # push:
  #   branches:
  #     - main
  # pull_request:
  workflow_dispatch:
#  schedule:
#    - cron: "05 13 30 10 Thu" # At 13:05 on October 30th if it is a Thursday

jobs: 
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
          echo "Event trigger: ${{ github.event_name }}"
        